
[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_source = '''
	let g:airline_powerline_fonts = 1
	set laststatus=2
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'Shougo/vimproc'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
hook_add = '''
let g:vimfiler_execute_file_list={}
let g:vimfiler_execute_file_list["_"]="C:/Windows/explorer.exe"

'''
